<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--
    
    net46;
      net463;
    
      net47;
      net471;
    
    -->

    <Company>BitMinistry.com</Company>
    <Authors>Andrew Rebane</Authors>
    <Copyright>Copyright © 2025</Copyright>

    <Product>BitMinistry.OpenAi</Product>
    <Title>BitMinistry.OpenAi</Title>
    <Description>a lightweight Open AI adapter</Description>


    <PackageProjectUrl>http://www.bitMinistry.com</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>    
    <PackageTags>utility helper middlewear infra crosscutting</PackageTags>


    <AssemblyVersion>1.0.0</AssemblyVersion>
    <PackageVersion>1.0.0</PackageVersion>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>BitMinistry.OpenAi.snk</AssemblyOriginatorKeyFile>

  </PropertyGroup>

  <ItemGroup>


    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" Condition="'$(TargetFramework)' == 'net461' Or '$(TargetFramework)' == 'net462' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netstandard2.0'" />



    <None Include="README.md" Pack="true" PackagePath="" />


    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NewsAI.git\BitMinistry.CoreNet.Web\BitMinistry.CoreNet.Web.csproj" />
  </ItemGroup>


  <Target Name="RenamePack" AfterTargets="Pack">
    
    <Move SourceFiles="$(OutputPath)$(PackageId).$(PackageVersion).nupkg" DestinationFiles="$(OutputPath)package.nupkg" />

  </Target>




</Project>


